name: Build App

on:
  push:
    branches:
      - autobuild3

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: autobuild3

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21.x'

    - name: Install dependencies
      run: go get .

    - name: Build
      run: |
        chmod +x ./build.sh
        ./build.sh

    - name: Upload builds
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./bin/anchor-*
        file_glob: true
        tag: ${{ github.ref }}
        target_commit: autobuild3