name: Build App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: main

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21.x'

    - name: Install dependencies
      run: go get .

    - name: Build
      run: |
        platforms=("windows/amd64" "linux/amd64" "darwin/amd64" "darwin/arm64" "linux/arm64" "windows/arm64")
        for platform in "${platforms[@]}"; do
            GOOS=${platform%/*}
            GOARCH=${platform#*/}
            env GOOS=$GOOS GOARCH=$GOARCH go build -o ./bin/anchor-$GOOS-$GOARCH .
        done

    - name: Upload builds
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./bin/anchor-*
        file_glob: true
        tag: ${{ github.ref }}
        target_commit: main